### ISSUE TITLE
Feature?: Incorporate the nonce into src requests

### ISSUE THREAD

**Issue by redevill** [frux/express-csp-header#8]
Hello,

Producing the nonce in the header is nice. However, getting it into requested scripts and styles is still not simple.

How about attaching to the fetch middleware of express, to add the nonce to script and style files... 
(Browser caching might be an issue...)
Angular dynamic application of styles, an issue.

Just thought I throw the idea.
Thanks

**Comment by frux** [comment]
Hi @redevill! What is the fetch middleware of express? Haven't heard about it.

**Comment by redevill** [comment]
Sorry, brain working faster than my fingers, got a bit muddled. Especially since set up scrips allow one to use functions without necessarily understanding how they work.

What I do understand, is that there is a problem to get a changing nonce into the script tags, and css,  that is delivered to the browser (dependent on mechanism!). In my haste, I simply thought to have express perform this function as an addition to the middleware. In a similar way the header is added. 

Here is where my knowledge gets fuzzy. Potentially the css and javascript could have different delivery mechanisms and come from different servers... then I can't see how to achieve the matching nonce injection.

BUT IF, it comes from the same server, and you are using, say Angular, would it not be possible to coordinate the web/file server with express, such that the returned scripts & css that are tagged with a matching nonce? This was the thought, anyway. 

I don't know enough about the serving mechanisms to know how viable the idea is.
Hence the "Throwing" the idea out there for someone with more knowledge.
Thanks

**Comment by frux** [comment]
The only thing you need to do is add `nonce` attribute to your html tags which include scripts or styles. You don't need (and afaik you can't) specify nonce in scripts or styles.

**Comment by frux** [comment]
Close this issue due to inactivity
